# Generated by Django 2.2 on 2019-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191107_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала работы'),
        ),
    ]
