# Generated by Django 2.2 on 2019-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191113_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания работы'),
        ),
    ]
